### ISSUE TITLE
SAT-Math corpus includes incomplete data

### ISSUE THREAD

**Issue by jiexiongw** [microsoft/AGIEval#1]
in sat-math corpus, it happens to have incomplete question, which may make it insufficient to solve. 

{"passage": "", "question": "Which of the following is equivalent to the expression above?" ...

**Comment by ruixiangcui** [comment]
Hi jiexiongw, thank you for noticing the missed information! We found two instances of such an error with indices [4, 115] and just updated the data in the repo. Please use git pull to get the new updates.
