### ISSUE TITLE
dirty data in gaokao-bio and gaokao-geo

### ISSUE THREAD

**Issue by ADMIN2021020121** [microsoft/AGIEval#13]
![image](https://github.com/microsoft/AGIEval/assets/96457562/6a3a36c5-4325-4833-92c4-bd42ab404474)

![image](https://github.com/microsoft/AGIEval/assets/96457562/9b2def5f-a784-416a-a16e-c55418397b5b)

```[tasklist]
### Tasks
```

**Comment by ADMIN2021020121** [comment]
![image](https://github.com/microsoft/AGIEval/assets/96457562/f1fed23f-2bc2-446d-9795-5a4b0fdf71fa)
![image](https://github.com/microsoft/AGIEval/assets/96457562/5d573ada-1dae-4b1f-8cb5-366d75d28a27)

**Comment by ruixiangcui** [comment]
Hi @ADMIN2021020121, thank you very much for your feedback! I have already updated the repo and please pull to get the latest data.
