### ISSUE TITLE
How to post-processed data from raw JEC-QA data?

### ISSUE THREAD

**Issue by wjfwzzc** [microsoft/AGIEval#14]
I already download JEC-QA data, so how can I generate the post-processed data from it? Could you provide the official processing scripts?

**Comment by ruixiangcui** [comment]
Hi @wjfwzzc, we are delighted to inform you that JEC-QA datasets (KD, CA; 1,000 instances each from training sets) can be downloaded from this repository directly. 

We kindly request you to comply with the following rules:

1. Most of the questions in JEC-QA are obtained from actual Chinese judicial exams and some practice tests compiled by commercial institutions. Therefore, this dataset is intended for academic research only and commercial use is strictly prohibited.
2. We hope that the users of JEC-QA can acknowledge the work by citing the paper [JEC-QA](https://arxiv.org/abs/1911.12011).
