### ISSUE TITLE
Dirty data in gaokao-physics

### ISSUE THREAD

**Issue by MrZhengXin** [microsoft/AGIEval#15]
https://github.com/microsoft/AGIEval/blob/b1187aa0bf0e14125cb9a6c58f25288a4e272e64/data/v1/gaokao-physics.jsonl#L4C4-L4C4

The correct answer shall be ["A", "D"] rather than ["B", "C"], as stated in https://edu.sina.cn/gaokao/qsbk/2022-06-01/detail-imizirau6064163.d.html

**Comment by ruixiangcui** [comment]
Dear @MrZhengXin , thank you for spotting the error in Gaokao-physics. We have already fixed the error. Please pull the commit to update the dataset.
