### ISSUE TITLE
Dirty data in the dataset.

### ISSUE THREAD

**Issue by chengeharrison** [microsoft/AGIEval#16]
Hi, when I parse the dataset's `options`, I found unnormal behavior which the length of `options` is different from others in the same subcatrgory.

1. In `gaokao-chemistry.jsonl`, [line 190](https://github.com/microsoft/AGIEval/blob/main/data/v1/gaokao-chemistry.jsonl#L190)'s `options` include invalid options (which is actually the question's analysis). The length of `options` is actually 7 not 4.
![20230817-170517](https://github.com/microsoft/AGIEval/assets/70520919/c5b01d1a-6791-41a2-88d1-745c510a661e)
After option "D", there is a fifth option.
![20230817-170556](https://github.com/microsoft/AGIEval/assets/70520919/0b10ad40-9b65-467f-9a81-ea9b3f3d668c)

2. Missing options.
- In `sat-en-without-passage.jsonl`, [line 17](https://github.com/microsoft/AGIEval/blob/main/data/v1/sat-en-without-passage.jsonl#L17)'s `options` miss option D which should be "They may increase in value as those same resources become rare on Earth." [reference](https://soflotutors.com/explanations/official-sat-practice-test-1/reading/sat-official-1_s1_q52)
![20230817-171359](https://github.com/microsoft/AGIEval/assets/70520919/74fb2164-5799-42e7-a0f4-2b46ed9c37d5)

- In `sat-en-without-passage.jsonl`, [line 57](https://github.com/microsoft/AGIEval/blob/main/data/v1/sat-en-without-passage.jsonl#L57)'s `options` miss option D which should be "No, because the data do not indicate whether the honeybees had been infected with mites." while the label is "D". [reference](https://soflotutors.com/explanations/official-sat-practice-test-3/reading/s1-q52-sat-3)
![img_v2_83f511ea-27ce-45ab-a43e-df788a0fbe0g](https://github.com/microsoft/AGIEval/assets/70520919/5f4a293e-df4a-45a3-bc7c-70deaff52d88)

- In `sat-en-without-passage.jsonl`, [line 98](https://github.com/microsoft/AGIEval/blob/main/data/v1/sat-en-without-passage.jsonl#L98)'s `options` miss option D which should be "Published theories of scientists who developed earlier models of the Venus flytrap". You can refer to question 11 in [reference](https://wikyhub.com/read.php?aid=oMHbQCBb3Ky).
![img_v2_5ad1f5fc-cd5d-4a2d-a607-94296e2c4abg](https://github.com/microsoft/AGIEval/assets/70520919/c2bba31c-b049-48ff-b9d4-458a0f570844)

The same goes for `sat-en.jsonl` in line 17, 57 and 98.

3. In `jec-qa-kd.jsonl`, [line 212](https://github.com/microsoft/AGIEval/blob/main/data/v1/jec-qa-kd.jsonl#L212)'s `label` is empty. The content is also dirty.
![img_v2_e9f4cde5-a876-465b-9968-f743fb24040g](https://github.com/microsoft/AGIEval/assets/70520919/3824b6bd-691a-48f2-8544-ca9123c74cfd)
![img_v2_46ad402b-05a6-4605-900f-c2b089fd082g](https://github.com/microsoft/AGIEval/assets/70520919/09ff6bc3-52b2-4400-bb57-6ada48ff7888)

**Comment by ruixiangcui** [comment]
Thank you for your corrections! Scraping, annotating, and reformatting can be laborious and time-consuming. Your efforts have played a pivotal role in enhancing our benchmark. We have updated the three datasets on GitHub. Please make sure to update them as well.
