### ISSUE TITLE
parse_result error in gaokao-physics-zero-shot

### ISSUE THREAD

**Issue by hejujie** [microsoft/AGIEval#3]
![image](https://user-images.githubusercontent.com/29149911/233282787-4fbe5b7c-5b58-4d1d-af54-ff59c958e250.png)
model output is :
"model_output": "选项 (B) $3.3\\mathrm{MeV}$。", "parse_result": ["B", "M", "V"], "label": "B", "is_correct": false；
as gaokao-physics has multi-answer, it will take all uppercase letters， which makes the correct answer become an error.
```python
def parse_qa_multiple_answer(string, setting_name):
    if setting_name == "few-shot-CoT":
        string = extract_last_line(string)
    pattern = "\(*([A-Z])\)*"
    match = re.findall(pattern, string)
    if match:
        return match
    return []
```
maybe we can make a candidate answer list like ["A", "B", "C", "D", "E", "F"] to reduce the prob of error?
```python
def parse_qa_multiple_answer(string, setting_name):
    if setting_name == "few-shot-CoT":
        string = extract_last_line(string)
    pattern = "\(*([A-F])\)*"
    match = re.findall(pattern, string)
    if match:
        return match
    return []
```

**Comment by ruixiangcui** [comment]
Thanks for the recommendation. Would you like to make a pull request?

**Comment by ruixiangcui** [comment]
I just incorporated your suggestion in the new commit. Thank you!
