### ISSUE TITLE
Bug in Dataset Loader for Few-Shot Multiple Choice Questions

### ISSUE THREAD

**Issue by Leymore** [microsoft/AGIEval#4]
I've noticed that the current code uses the expression `demo + question`. However, I believe the correct expression should be `demo + question_input`. By using `demo + question`, the previously defined `question_input` is not being utilized and some multiple-choice questions may lack options in the prompt. Please consider updating the code to reflect this change for proper functionality. Thank you!

https://github.com/microsoft/AGIEval/blob/main/src/dataset_loader.py#L215

**Comment by ruixiangcui** [comment]
I just incorporated your suggestion in the new commit. Thank you!
