### ISSUE TITLE
how to generate the output_path?I run the run_prediction.py

### ISSUE THREAD

**Issue by XiaoHeiWuDiMachineLearning** [microsoft/AGIEval#5]
![1682307197390](https://user-images.githubusercontent.com/61000792/233893930-5d703350-6343-4255-a502-e6b9eb88c0f2.png)

**Comment by skywalkerytx** [comment]
`few-shot` needs to be enabled in `setting_name_list`.

they made it a comment so output_path is never used

**Comment by XiaoHeiWuDiMachineLearning** [comment]
How can we generate the './outputs/davinci-003\\outputs\\predict.davinci-003.sat-math.zero-shot.jsonl',I just can generate "predict.davinci-003.sat-math.zero-shot.first_stage.jsonl" and "predict.davinci-003.sat-math.zero-shot-CoT.first_stage.jsonl",so I can not run the post_process_and_evaluation.py.Excuse me,how can I do？
![1682322853187](https://user-images.githubusercontent.com/61000792/233932777-9414437f-46a3-4a07-a17e-88e2ad814bee.png)

**Comment by XiaoHeiWuDiMachineLearning** [comment]
How can we generate the './outputs/davinci-003\outputs\predict.davinci-003.sat-math.zero-shot.jsonl',I just can generate "predict.davinci-003.sat-math.zero-shot.first_stage.jsonl" and "predict.davinci-003.sat-math.zero-shot-CoT.first_stage.jsonl",so I can not run the post_process_and_evaluation.py.Excuse me,how can I do？
![1682323162842](https://user-images.githubusercontent.com/61000792/233933980-b878a37b-7d1b-4619-91a1-0386f419acff.png)

**Comment by ruixiangcui** [comment]
Hi @XiaoHeiWuDiMachineLearning, to generate the second stage output, in your case, './outputs/davinci-003\outputs\predict.davinci-003.sat-math.zero-shot.jsonl', you need to set https://github.com/microsoft/AGIEval/blob/main/run_prediction.py#L133 to True and https://github.com/microsoft/AGIEval/blob/main/run_prediction.py#L134 to False.
